# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      # 设置 Maven Settings
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          profiles: >
            [
              {
                "id": "ci",
                "properties": {
                  "altSnapshotDeploymentRepository": "${{ secrets.ALT_SNAPSHOT_DEPLOYMENT_REPOSITORY }}",
                  "altReleaseDeploymentRepository": "${{ secrets.ALT_RELEASE_DEPLOYMENT_REPOSITORY }}",
                  "gpg.keyname": "${{ steps.gpg-key-id.outputs.gpgKeyId }}",
                  "gpg.passphrase": "${{ secrets.GPG_PASSPHRASE }}"
                }
              }
            ]
          servers: >
            [
              {
                "id": "ossrh",
                "username": "${{ secrets.MVN_SERVER_USER }}",
                "password": "${{ secrets.MVN_SERVER_PASSWORD }}"
              }
            ]
          repositories: >
            [
              {
                "id": "ossrh-releases",
                "name": "ossrh releases",
                "url": "https://s01.oss.sonatype.org/content/repositories/releases/",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "ossrh-snapshots",
                "name": "ossrh snapshots",
                "url": "https://s01.oss.sonatype.org/content/repositories/snapshots/",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
      - name: Cat Setting.xml
        run : cat /home/runner/.m2/settings.xml
      - name: Deploy with Maven
        run: mvn -B deploy -Pci --file pom.xml
